version: '3.3'
services:
  httpd:
    image: "n0r1skcom/bosnd-httpd:1.1"
    ports:
      - "80:80"
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  tomcat:
    image: "n0r1skcom/bosnd-tomcat:1.0"
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    deploy:
      replicas: 2
      labels:
        context: "/demo"
        port: "8009"
    networks:
      - net
networks:
  net:
    driver: overlay
    attachable: true